<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GnuboardSeeder extends Seeder
{
    public function run()
    {
        // 기본 설정
        DB::table('g5_config')->insert([
            'cf_title' => '그누보드5 Laravel',
            'cf_theme' => '',
            'cf_admin' => 'admin',
            'cf_admin_email' => 'admin@example.com',
            'cf_admin_email_name' => '관리자',
            'cf_add_script' => '',
            'cf_use_point' => 1,
            'cf_point_term' => 0,
            'cf_use_copy_log' => '',
            'cf_use_email_certify' => 0,
            'cf_login_point' => 100,
            'cf_cut_name' => '15',
            'cf_nick_modify' => '60',
            'cf_new_skin' => 'basic',
            'cf_new_rows' => '15',
            'cf_search_skin' => 'basic',
            'cf_connect_skin' => 'basic',
            'cf_faq_skin' => 'basic',
            'cf_read_point' => -1,
            'cf_write_point' => 10,
            'cf_comment_point' => 5,
            'cf_download_point' => -20,
            'cf_write_pages' => 10,
            'cf_mobile_pages' => 5,
            'cf_link_target' => '_blank',
            'cf_bbs_rewrite' => '',
            'cf_delay_sec' => '30',
            'cf_filter' => '',
            'cf_possible_ip' => '',
            'cf_intercept_ip' => '',
            'cf_analytics' => '',
            'cf_add_meta' => '',
            'cf_syndi_token' => 0,
            'cf_syndi_except' => 0,
            'cf_member_skin' => 0,
            'cf_use_homepage' => 0,
            'cf_req_homepage' => 0,
            'cf_use_tel' => 0,
            'cf_req_tel' => 0,
            'cf_use_hp' => 1,
            'cf_req_hp' => 0,
            'cf_use_addr' => 0,
            'cf_req_addr' => 0,
            'cf_use_signature' => 1,
            'cf_req_signature' => 0,
            'cf_use_profile' => 1,
            'cf_req_profile' => 0,
            'cf_register_level' => 2,
            'cf_register_point' => 1000,
            'cf_icon_level' => 2,
            'cf_use_recommend' => 0,
            'cf_recommend_point' => 0,
            'cf_leave_day' => 30,
            'cf_search_part' => 10000,
            'cf_email_use' => 1,
            'cf_email_wr_super_admin' => 0,
            'cf_email_wr_group_admin' => 0,
            'cf_email_wr_board_admin' => 0,
            'cf_email_wr_write' => 0,
            'cf_email_wr_comment_all' => 0,
            'cf_email_mb_super_admin' => 0,
            'cf_email_mb_member' => 0,
            'cf_email_po_super_admin' => 0,
            'cf_prohibit_id' => 0,
            'cf_prohibit_email' => 0,
            'cf_new_del' => 30,
            'cf_login_minutes' => 10,
            'cf_image_extension' => 0,
            'cf_flash_extension' => 0,
            'cf_movie_extension' => 0,
            'cf_formmail_is_member' => 1,
            'cf_page_rows' => '15',
            'cf_mobile_page_rows' => '15',
            'cf_visit' => '오늘:1,어제:0,최대:1,전체:1',
            'cf_max_po_id' => '0',
            'cf_stipulation' => '제1조(목적)\r\n이 약관은...',
            'cf_privacy' => '개인정보처리방침 내용...',
            'cf_open_modify' => 0,
            'cf_memo_send_point' => 500,
            'cf_mobile_new_skin' => 'basic',
            'cf_mobile_search_skin' => 'basic',
            'cf_mobile_connect_skin' => 'basic',
            'cf_mobile_faq_skin' => 'basic',
            'cf_mobile_member_skin' => 'basic',
            'cf_captcha_mp3' => 'basic',
            'cf_editor' => 'smarteditor2',
            'cf_cert_use' => 0,
            'cf_cert_find' => '',
            'cf_cert_ipin' => '',
            'cf_cert_hp' => '',
            'cf_cert_kg_cd' => '',
            'cf_cert_kg_mid' => '',
            'cf_cert_req' => '',
            'cf_sms_use' => '',
            'cf_sms_type' => '',
            'cf_icode_id' => '',
            'cf_icode_pw' => '',
            'cf_icode_server_ip' => '',
            'cf_icode_server_port' => '',
            'cf_icode_token_key' => '',
            'cf_googl_shorturl_apikey' => '',
            'cf_social_login_use' => '',
            'cf_social_servicelist' => '',
            'cf_payco_clientid' => '',
            'cf_payco_secret' => '',
            'cf_facebook_appid' => '',
            'cf_facebook_secret' => '',
            'cf_twitter_key' => '',
            'cf_twitter_secret' => '',
            'cf_google_clientid' => '',
            'cf_google_secret' => '',
            'cf_naver_clientid' => '',
            'cf_naver_secret' => '',
            'cf_kakao_rest_key' => '',
            'cf_kakao_client_secret' => '',
            'cf_kakao_js_apikey' => '',
            'cf_captcha' => 'kcaptcha',
            'cf_recaptcha_site_key' => '',
            'cf_recaptcha_secret_key' => '',
            'cf_1_subj' => '',
            'cf_2_subj' => '',
            'cf_3_subj' => '',
            'cf_4_subj' => '',
            'cf_5_subj' => '',
            'cf_6_subj' => '',
            'cf_7_subj' => '',
            'cf_8_subj' => '',
            'cf_9_subj' => '',
            'cf_10_subj' => '',
            'cf_1' => '',
            'cf_2' => '',
            'cf_3' => '',
            'cf_4' => '',
            'cf_5' => '',
            'cf_6' => '',
            'cf_7' => '',
            'cf_8' => '',
            'cf_9' => '',
            'cf_10' => '',
        ]);

        // 관리자 계정 생성
        DB::table('g5_member')->insert([
            'mb_id' => 'admin',
            'mb_password' => Hash::make('admin123'),
            'mb_name' => '최고관리자',
            'mb_nick' => '최고관리자',
            'mb_nick_date' => now(),
            'mb_email' => 'admin@example.com',
            'mb_homepage' => '',
            'mb_level' => 10,
            'mb_sex' => '',
            'mb_birth' => '',
            'mb_tel' => '',
            'mb_hp' => '',
            'mb_certify' => '',
            'mb_adult' => 0,
            'mb_dupinfo' => '',
            'mb_zip1' => '',
            'mb_zip2' => '',
            'mb_addr1' => '',
            'mb_addr2' => '',
            'mb_addr3' => '',
            'mb_addr_jibeon' => '',
            'mb_signature' => '',
            'mb_recommend' => '',
            'mb_point' => 1000000,
            'mb_today_login' => now(),
            'mb_login_ip' => '127.0.0.1',
            'mb_datetime' => now(),
            'mb_ip' => '127.0.0.1',
            'mb_leave_date' => '0000-00-00 00:00:00',
            'mb_intercept_date' => '',
            'mb_email_certify' => now(),
            'mb_email_certify2' => '',
            'mb_memo' => '',
            'mb_lost_certify' => '',
            'mb_mailling' => 1,
            'mb_sms' => 1,
            'mb_open' => 1,
            'mb_open_date' => now(),
            'mb_profile' => '',
            'mb_memo_call' => '',
            'mb_memo_cnt' => 0,
            'mb_scrap_cnt' => 0,
            'mb_1' => '',
            'mb_2' => '',
            'mb_3' => '',
            'mb_4' => '',
            'mb_5' => '',
            'mb_6' => '',
            'mb_7' => '',
            'mb_8' => '',
            'mb_9' => '',
            'mb_10' => '',
        ]);

        // 일반 회원 생성
        DB::table('g5_member')->insert([
            'mb_id' => 'test',
            'mb_password' => Hash::make('test123'),
            'mb_name' => '테스트',
            'mb_nick' => '테스트유저',
            'mb_nick_date' => now(),
            'mb_email' => 'test@example.com',
            'mb_homepage' => '',
            'mb_level' => 2,
            'mb_sex' => '',
            'mb_birth' => '',
            'mb_tel' => '',
            'mb_hp' => '',
            'mb_certify' => '',
            'mb_adult' => 0,
            'mb_dupinfo' => '',
            'mb_zip1' => '',
            'mb_zip2' => '',
            'mb_addr1' => '',
            'mb_addr2' => '',
            'mb_addr3' => '',
            'mb_addr_jibeon' => '',
            'mb_signature' => '',
            'mb_recommend' => '',
            'mb_point' => 1000,
            'mb_today_login' => now(),
            'mb_login_ip' => '127.0.0.1',
            'mb_datetime' => now(),
            'mb_ip' => '127.0.0.1',
            'mb_leave_date' => '0000-00-00 00:00:00',
            'mb_intercept_date' => '',
            'mb_email_certify' => now(),
            'mb_email_certify2' => '',
            'mb_memo' => '',
            'mb_lost_certify' => '',
            'mb_mailling' => 1,
            'mb_sms' => 1,
            'mb_open' => 1,
            'mb_open_date' => now(),
            'mb_profile' => '',
            'mb_memo_call' => '',
            'mb_memo_cnt' => 0,
            'mb_scrap_cnt' => 0,
            'mb_1' => '',
            'mb_2' => '',
            'mb_3' => '',
            'mb_4' => '',
            'mb_5' => '',
            'mb_6' => '',
            'mb_7' => '',
            'mb_8' => '',
            'mb_9' => '',
            'mb_10' => '',
        ]);

        // 그룹 생성
        DB::table('g5_group')->insert([
            'gr_id' => 'community',
            'gr_subject' => '커뮤니티',
            'gr_device' => 'both',
            'gr_admin' => '',
            'gr_use_access' => 0,
            'gr_order' => 0,
            'gr_1_subj' => '',
            'gr_2_subj' => '',
            'gr_3_subj' => '',
            'gr_4_subj' => '',
            'gr_5_subj' => '',
            'gr_6_subj' => '',
            'gr_7_subj' => '',
            'gr_8_subj' => '',
            'gr_9_subj' => '',
            'gr_10_subj' => '',
            'gr_1' => '',
            'gr_2' => '',
            'gr_3' => '',
            'gr_4' => '',
            'gr_5' => '',
            'gr_6' => '',
            'gr_7' => '',
            'gr_8' => '',
            'gr_9' => '',
            'gr_10' => '',
        ]);

        // 게시판 생성
        $boards = [
            [
                'bo_table' => 'free',
                'gr_id' => 'community',
                'bo_subject' => '자유게시판',
                'bo_mobile_subject' => '자유게시판',
                'bo_device' => 'both',
                'bo_admin' => '',
                'bo_use_category' => 1,
                'bo_category_list' => '일반|유머|정보',
                'bo_use_sideview' => 1,
                'bo_use_file_content' => 0,
                'bo_use_secret' => 1,
                'bo_use_dhtml_editor' => 1,
                'bo_use_rss_view' => 1,
                'bo_use_good' => 1,
                'bo_use_nogood' => 1,
                'bo_use_name' => 0,
                'bo_use_signature' => 1,
                'bo_use_ip_view' => 0,
                'bo_use_list_view' => 0,
                'bo_use_list_file' => 0,
                'bo_use_list_content' => 0,
                'bo_table_width' => 100,
                'bo_subject_len' => 60,
                'bo_mobile_subject_len' => 30,
                'bo_page_rows' => 15,
                'bo_mobile_page_rows' => 15,
                'bo_new' => 24,
                'bo_hot' => 100,
                'bo_image_width' => 600,
                'bo_skin' => 'basic',
                'bo_mobile_skin' => 'basic',
                'bo_upload_size' => 1048576,
                'bo_reply_order' => 1,
                'bo_use_search' => 1,
                'bo_order' => 0,
                'bo_upload_count' => 2,
                'bo_use_email' => 0,
                'bo_use_cert' => '',
                'bo_use_sns' => 0,
                'bo_use_captcha' => 0,
                'bo_sort_field' => '',
            ],
            [
                'bo_table' => 'notice',
                'gr_id' => 'community',
                'bo_subject' => '공지사항',
                'bo_mobile_subject' => '공지사항',
                'bo_device' => 'both',
                'bo_admin' => '',
                'bo_list_level' => 0,
                'bo_read_level' => 0,
                'bo_write_level' => 10,
                'bo_reply_level' => 10,
                'bo_comment_level' => 10,
                'bo_use_category' => 0,
                'bo_category_list' => '',
                'bo_use_sideview' => 1,
                'bo_use_file_content' => 0,
                'bo_use_secret' => 0,
                'bo_use_dhtml_editor' => 1,
                'bo_use_rss_view' => 1,
                'bo_use_good' => 0,
                'bo_use_nogood' => 0,
                'bo_use_name' => 0,
                'bo_use_signature' => 0,
                'bo_use_ip_view' => 0,
                'bo_use_list_view' => 0,
                'bo_use_list_file' => 0,
                'bo_use_list_content' => 0,
                'bo_table_width' => 100,
                'bo_subject_len' => 60,
                'bo_mobile_subject_len' => 30,
                'bo_page_rows' => 15,
                'bo_mobile_page_rows' => 15,
                'bo_new' => 24,
                'bo_hot' => 100,
                'bo_image_width' => 600,
                'bo_skin' => 'basic',
                'bo_mobile_skin' => 'basic',
                'bo_upload_size' => 1048576,
                'bo_reply_order' => 1,
                'bo_use_search' => 1,
                'bo_order' => 0,
                'bo_upload_count' => 2,
                'bo_use_email' => 0,
                'bo_use_cert' => '',
                'bo_use_sns' => 0,
                'bo_use_captcha' => 0,
                'bo_sort_field' => '',
            ],
            [
                'bo_table' => 'gallery',
                'gr_id' => 'community',
                'bo_subject' => '갤러리',
                'bo_mobile_subject' => '갤러리',
                'bo_device' => 'both',
                'bo_admin' => '',
                'bo_use_category' => 1,
                'bo_category_list' => '풍경|인물|동물',
                'bo_use_sideview' => 1,
                'bo_use_file_content' => 0,
                'bo_use_secret' => 0,
                'bo_use_dhtml_editor' => 1,
                'bo_use_rss_view' => 0,
                'bo_use_good' => 1,
                'bo_use_nogood' => 1,
                'bo_use_name' => 0,
                'bo_use_signature' => 0,
                'bo_use_ip_view' => 0,
                'bo_use_list_view' => 1,
                'bo_use_list_file' => 1,
                'bo_use_list_content' => 0,
                'bo_table_width' => 100,
                'bo_subject_len' => 60,
                'bo_mobile_subject_len' => 30,
                'bo_page_rows' => 12,
                'bo_mobile_page_rows' => 12,
                'bo_new' => 24,
                'bo_hot' => 100,
                'bo_image_width' => 600,
                'bo_skin' => 'gallery',
                'bo_mobile_skin' => 'gallery',
                'bo_gallery_cols' => 4,
                'bo_gallery_width' => 200,
                'bo_gallery_height' => 150,
                'bo_mobile_gallery_width' => 100,
                'bo_mobile_gallery_height' => 100,
                'bo_upload_size' => 1048576,
                'bo_reply_order' => 1,
                'bo_use_search' => 1,
                'bo_order' => 0,
                'bo_upload_count' => 10,
                'bo_use_email' => 0,
                'bo_use_cert' => '',
                'bo_use_sns' => 0,
                'bo_use_captcha' => 0,
                'bo_sort_field' => '',
            ],
            [
                'bo_table' => 'qa',
                'gr_id' => 'community',
                'bo_subject' => 'Q&A',
                'bo_mobile_subject' => 'Q&A',
                'bo_device' => 'both',
                'bo_admin' => '',
                'bo_use_category' => 1,
                'bo_category_list' => '일반|기술|기타',
                'bo_use_sideview' => 1,
                'bo_use_file_content' => 0,
                'bo_use_secret' => 0,
                'bo_use_dhtml_editor' => 1,
                'bo_use_rss_view' => 0,
                'bo_use_good' => 1,
                'bo_use_nogood' => 0,
                'bo_use_name' => 0,
                'bo_use_signature' => 0,
                'bo_use_ip_view' => 0,
                'bo_use_list_view' => 0,
                'bo_use_list_file' => 0,
                'bo_use_list_content' => 0,
                'bo_table_width' => 100,
                'bo_subject_len' => 60,
                'bo_mobile_subject_len' => 30,
                'bo_page_rows' => 15,
                'bo_mobile_page_rows' => 15,
                'bo_new' => 24,
                'bo_hot' => 100,
                'bo_image_width' => 600,
                'bo_skin' => 'basic',
                'bo_mobile_skin' => 'basic',
                'bo_upload_size' => 1048576,
                'bo_reply_order' => 1,
                'bo_use_search' => 1,
                'bo_order' => 0,
                'bo_upload_count' => 2,
                'bo_use_email' => 0,
                'bo_use_cert' => '',
                'bo_use_sns' => 0,
                'bo_use_captcha' => 0,
                'bo_sort_field' => '',
            ],
        ];

        foreach ($boards as $board) {
            // 기본값 설정
            $defaults = [
                'bo_list_level' => 0,
                'bo_read_level' => 0,
                'bo_write_level' => 1,
                'bo_reply_level' => 1,
                'bo_comment_level' => 1,
                'bo_upload_level' => 1,
                'bo_download_level' => 1,
                'bo_html_level' => 1,
                'bo_link_level' => 1,
                'bo_count_delete' => 0,
                'bo_count_modify' => 0,
                'bo_read_point' => -1,
                'bo_write_point' => 10,
                'bo_comment_point' => 5,
                'bo_download_point' => -20,
                'bo_use_category' => 0,
                'bo_category_list' => '',
                'bo_use_sideview' => 0,
                'bo_use_file_content' => 0,
                'bo_use_secret' => 0,
                'bo_use_dhtml_editor' => 0,
                'bo_select_editor' => '',
                'bo_use_rss_view' => 0,
                'bo_use_good' => 0,
                'bo_use_nogood' => 0,
                'bo_use_name' => 0,
                'bo_use_signature' => 0,
                'bo_use_ip_view' => 0,
                'bo_use_list_view' => 0,
                'bo_use_list_file' => 0,
                'bo_use_list_content' => 0,
                'bo_table_width' => 100,
                'bo_subject_len' => 60,
                'bo_mobile_subject_len' => 30,
                'bo_page_rows' => 15,
                'bo_mobile_page_rows' => 15,
                'bo_new' => 24,
                'bo_hot' => 100,
                'bo_image_width' => 600,
                'bo_skin' => 'basic',
                'bo_mobile_skin' => 'basic',
                'bo_include_head' => '',
                'bo_include_tail' => '',
                'bo_content_head' => '',
                'bo_mobile_content_head' => '',
                'bo_content_tail' => '',
                'bo_mobile_content_tail' => '',
                'bo_insert_content' => '',
                'bo_gallery_cols' => 4,
                'bo_gallery_width' => 125,
                'bo_gallery_height' => 100,
                'bo_mobile_gallery_width' => 125,
                'bo_mobile_gallery_height' => 100,
                'bo_upload_size' => 1048576,
                'bo_reply_order' => 1,
                'bo_use_search' => 0,
                'bo_order' => 0,
                'bo_count_write' => 0,
                'bo_count_comment' => 0,
                'bo_write_min' => 0,
                'bo_write_max' => 0,
                'bo_comment_min' => 0,
                'bo_comment_max' => 0,
                'bo_notice' => '',
                'bo_upload_count' => 2,
                'bo_use_email' => 0,
                'bo_use_cert' => '',
                'bo_use_sns' => 0,
                'bo_use_captcha' => 0,
                'bo_sort_field' => '',
                'bo_1_subj' => '',
                'bo_2_subj' => '',
                'bo_3_subj' => '',
                'bo_4_subj' => '',
                'bo_5_subj' => '',
                'bo_6_subj' => '',
                'bo_7_subj' => '',
                'bo_8_subj' => '',
                'bo_9_subj' => '',
                'bo_10_subj' => '',
                'bo_1' => '',
                'bo_2' => '',
                'bo_3' => '',
                'bo_4' => '',
                'bo_5' => '',
                'bo_6' => '',
                'bo_7' => '',
                'bo_8' => '',
                'bo_9' => '',
                'bo_10' => '',
            ];

            $boardData = array_merge($defaults, $board);
            DB::table('g5_board')->insert($boardData);
        }

        // 샘플 게시글 생성
        $posts = [
            [
                'board' => 'notice',
                'wr_subject' => '그누보드5 Laravel 포팅 완료',
                'wr_content' => '그누보드5가 Laravel 프레임워크로 성공적으로 포팅되었습니다.',
                'mb_id' => 'admin',
                'wr_name' => '최고관리자',
                'wr_email' => 'admin@example.com',
            ],
            [
                'board' => 'free',
                'wr_subject' => '첫 번째 자유게시판 글입니다',
                'wr_content' => '자유게시판에 오신 것을 환영합니다.',
                'mb_id' => 'test',
                'wr_name' => '테스트유저',
                'wr_email' => 'test@example.com',
                'ca_name' => '일반',
            ],
            [
                'board' => 'qa',
                'wr_subject' => 'Laravel 포팅 관련 질문입니다',
                'wr_content' => '그누보드5를 Laravel로 포팅하는 과정에 대해 궁금한 점이 있습니다.',
                'mb_id' => 'test',
                'wr_name' => '테스트유저',
                'wr_email' => 'test@example.com',
                'ca_name' => '기술',
            ],
        ];

        foreach ($posts as $post) {
            $boardTable = $post['board'];
            unset($post['board']);
            
            $postData = array_merge([
                'wr_num' => -1,
                'wr_reply' => '',
                'wr_parent' => 0,
                'wr_is_comment' => 0,
                'wr_comment' => 0,
                'wr_comment_reply' => '',
                'ca_name' => '',
                'wr_option' => '',
                'wr_seo_title' => '',
                'wr_link1' => '',
                'wr_link2' => '',
                'wr_link1_hit' => 0,
                'wr_link2_hit' => 0,
                'wr_hit' => 0,
                'wr_good' => 0,
                'wr_nogood' => 0,
                'wr_password' => '',
                'wr_homepage' => '',
                'wr_datetime' => now(),
                'wr_file' => 0,
                'wr_last' => now()->format('Y-m-d H:i:s'),
                'wr_ip' => '127.0.0.1',
                'wr_facebook_user' => '',
                'wr_twitter_user' => '',
                'wr_1' => '',
                'wr_2' => '',
                'wr_3' => '',
                'wr_4' => '',
                'wr_5' => '',
                'wr_6' => '',
                'wr_7' => '',
                'wr_8' => '',
                'wr_9' => '',
                'wr_10' => '',
            ], $post);
            
            DB::table('g5_write_' . $boardTable)->insert($postData);
            
            // 게시판 글 수 증가
            DB::table('g5_board')->where('bo_table', $boardTable)->increment('bo_count_write');
        }
    }
}