<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('g5_config', function (Blueprint $table) {
            $table->id('cf_id');
            $table->string('cf_title', 255)->default('');
            $table->string('cf_theme', 100)->default('');
            $table->string('cf_admin', 100)->default('');
            $table->string('cf_admin_email', 100)->default('');
            $table->string('cf_admin_email_name', 100)->default('');
            $table->text('cf_add_script');
            $table->tinyInteger('cf_use_point')->default(0);
            $table->integer('cf_point_term')->default(0);
            $table->string('cf_use_copy_log', 255)->default('');
            $table->tinyInteger('cf_use_email_certify')->default(0);
            $table->integer('cf_login_point')->default(0);
            $table->string('cf_cut_name', 255)->default('');
            $table->string('cf_nick_modify', 255)->default('');
            $table->string('cf_new_skin', 255)->default('');
            $table->string('cf_new_rows', 255)->default('');
            $table->string('cf_search_skin', 255)->default('');
            $table->string('cf_connect_skin', 255)->default('');
            $table->string('cf_faq_skin', 255)->default('');
            $table->tinyInteger('cf_read_point')->default(0);
            $table->tinyInteger('cf_write_point')->default(0);
            $table->tinyInteger('cf_comment_point')->default(0);
            $table->tinyInteger('cf_download_point')->default(0);
            $table->tinyInteger('cf_write_pages')->default(0);
            $table->tinyInteger('cf_mobile_pages')->default(0);
            $table->string('cf_link_target', 255)->default('');
            $table->string('cf_bbs_rewrite', 255)->default('');
            $table->string('cf_delay_sec', 255)->default('');
            $table->string('cf_filter', 255)->default('');
            $table->string('cf_possible_ip', 255)->default('');
            $table->string('cf_intercept_ip', 255)->default('');
            $table->string('cf_analytics', 255)->default('');
            $table->text('cf_add_meta');
            $table->tinyInteger('cf_syndi_token')->default(0);
            $table->tinyInteger('cf_syndi_except')->default(0);
            $table->tinyInteger('cf_member_skin')->default(0);
            $table->tinyInteger('cf_use_homepage')->default(0);
            $table->tinyInteger('cf_req_homepage')->default(0);
            $table->tinyInteger('cf_use_tel')->default(0);
            $table->tinyInteger('cf_req_tel')->default(0);
            $table->tinyInteger('cf_use_hp')->default(0);
            $table->tinyInteger('cf_req_hp')->default(0);
            $table->tinyInteger('cf_use_addr')->default(0);
            $table->tinyInteger('cf_req_addr')->default(0);
            $table->tinyInteger('cf_use_signature')->default(0);
            $table->tinyInteger('cf_req_signature')->default(0);
            $table->tinyInteger('cf_use_profile')->default(0);
            $table->tinyInteger('cf_req_profile')->default(0);
            $table->tinyInteger('cf_register_level')->default(0);
            $table->tinyInteger('cf_register_point')->default(0);
            $table->tinyInteger('cf_icon_level')->default(0);
            $table->tinyInteger('cf_use_recommend')->default(0);
            $table->tinyInteger('cf_recommend_point')->default(0);
            $table->tinyInteger('cf_leave_day')->default(0);
            $table->tinyInteger('cf_search_part')->default(0);
            $table->tinyInteger('cf_email_use')->default(0);
            $table->tinyInteger('cf_email_wr_super_admin')->default(0);
            $table->tinyInteger('cf_email_wr_group_admin')->default(0);
            $table->tinyInteger('cf_email_wr_board_admin')->default(0);
            $table->tinyInteger('cf_email_wr_write')->default(0);
            $table->tinyInteger('cf_email_wr_comment_all')->default(0);
            $table->tinyInteger('cf_email_mb_super_admin')->default(0);
            $table->tinyInteger('cf_email_mb_member')->default(0);
            $table->tinyInteger('cf_email_po_super_admin')->default(0);
            $table->tinyInteger('cf_prohibit_id')->default(0);
            $table->tinyInteger('cf_prohibit_email')->default(0);
            $table->tinyInteger('cf_new_del')->default(0);
            $table->tinyInteger('cf_login_minutes')->default(0);
            $table->tinyInteger('cf_image_extension')->default(0);
            $table->tinyInteger('cf_flash_extension')->default(0);
            $table->tinyInteger('cf_movie_extension')->default(0);
            $table->tinyInteger('cf_formmail_is_member')->default(0);
            $table->string('cf_page_rows', 255)->default('');
            $table->string('cf_mobile_page_rows', 255)->default('');
            $table->string('cf_visit', 255)->default('');
            $table->string('cf_max_po_id', 255)->default('');
            $table->string('cf_stipulation', 255)->default('');
            $table->string('cf_privacy', 255)->default('');
            $table->tinyInteger('cf_open_modify')->default(0);
            $table->tinyInteger('cf_memo_send_point')->default(0);
            $table->string('cf_mobile_new_skin', 255)->default('');
            $table->string('cf_mobile_search_skin', 255)->default('');
            $table->string('cf_mobile_connect_skin', 255)->default('');
            $table->string('cf_mobile_faq_skin', 255)->default('');
            $table->string('cf_mobile_member_skin', 255)->default('');
            $table->tinyInteger('cf_captcha_mp3')->default(0);
            $table->tinyInteger('cf_editor')->default(0);
            $table->tinyInteger('cf_cert_use')->default(0);
            $table->string('cf_cert_find', 255)->default('');
            $table->string('cf_cert_ipin', 255)->default('');
            $table->string('cf_cert_hp', 255)->default('');
            $table->string('cf_cert_kg_cd', 255)->default('');
            $table->string('cf_cert_kg_mid', 255)->default('');
            $table->string('cf_cert_req', 255)->default('');
            $table->string('cf_sms_use', 255)->default('');
            $table->string('cf_sms_type', 255)->default('');
            $table->string('cf_icode_id', 255)->default('');
            $table->string('cf_icode_pw', 255)->default('');
            $table->string('cf_icode_server_ip', 255)->default('');
            $table->string('cf_icode_server_port', 255)->default('');
            $table->string('cf_icode_token_key', 255)->default('');
            $table->string('cf_googl_shorturl_apikey', 255)->default('');
            $table->string('cf_social_login_use', 255)->default('');
            $table->string('cf_social_servicelist', 255)->default('');
            $table->string('cf_payco_clientid', 255)->default('');
            $table->string('cf_payco_secret', 255)->default('');
            $table->string('cf_facebook_appid', 255)->default('');
            $table->string('cf_facebook_secret', 255)->default('');
            $table->string('cf_twitter_key', 255)->default('');
            $table->string('cf_twitter_secret', 255)->default('');
            $table->string('cf_google_clientid', 255)->default('');
            $table->string('cf_google_secret', 255)->default('');
            $table->string('cf_naver_clientid', 255)->default('');
            $table->string('cf_naver_secret', 255)->default('');
            $table->string('cf_kakao_rest_key', 255)->default('');
            $table->string('cf_kakao_client_secret', 255)->default('');
            $table->string('cf_kakao_js_apikey', 255)->default('');
            $table->string('cf_captcha', 255)->default('');
            $table->string('cf_recaptcha_site_key', 255)->default('');
            $table->string('cf_recaptcha_secret_key', 255)->default('');
            $table->text('cf_1_subj');
            $table->text('cf_2_subj');
            $table->text('cf_3_subj');
            $table->text('cf_4_subj');
            $table->text('cf_5_subj');
            $table->text('cf_6_subj');
            $table->text('cf_7_subj');
            $table->text('cf_8_subj');
            $table->text('cf_9_subj');
            $table->text('cf_10_subj');
            $table->text('cf_1');
            $table->text('cf_2');
            $table->text('cf_3');
            $table->text('cf_4');
            $table->text('cf_5');
            $table->text('cf_6');
            $table->text('cf_7');
            $table->text('cf_8');
            $table->text('cf_9');
            $table->text('cf_10');
        });
    }

    public function down()
    {
        Schema::dropIfExists('g5_config');
    }
};